### ISSUE TITLE
Additional information needed

### ISSUE THREAD

**Issue by naldarn** [madaeon01/LumiBee_beta#1]
In preparing to build the LumiBee, looking at the parts Resin_Container.STL, BottomVat.DXF, they do not list a material on the filename like the other files.

**Comment by madaeon01** [comment]
thanks, will fix this tomorrow.

**Comment by madaeon01** [comment]
I have updated the BOM file.
Resin_Container -> this holds the resin, so I recommend NOT to print it with FFF, or it will be damaged soon by the resin. I used our resin 3D Printer to make this part. You can also machine it from 14mm plexiglass, but it would be more expensive. 
AluPlate and BottomVat is 4mm aluminum CNC cut. 
NeopreneBorder, is 2mm hard neoprene CNC or laser cut.
