### ISSUE TITLE
How to contain resin

### ISSUE THREAD

**Issue by taylorzane** [madaeon01/LumiBee_beta#3]
I understand most of this build, but one thing I'm having trouble following is how the resin is held in the vat. The parts for the vat don't seem to have a bottom/sides to prevent the resin from flowing onto the phone/work surface. Are you using some sort of plastic wrap sandwiched between the vat pieces?

Thanks!

**Comment by taylorzane** [comment]
Another question would be what type of acrylic would you recommend for the windows? They appear to be dark red, but I imagine they're a little more specialized than that.

**Comment by madaeon01** [comment]
Hi, added info in https://github.com/madaeon01/LumiBee_beta/wiki/The-resin-VAT
Updated also BOM with plexiglass supplier and type.
