### ISSUE TITLE
BOM Missing Something

### ISSUE THREAD

**Issue by MxRemy** [madaeon01/LumiBee_beta#4]
There doesn't seem to be anything listed in the BOM to hold segment A and the various round connectors together. The longest part listed in the BOM is the m3x40 screws, and even those aren't half as long as they'd need to be to reach all the way across segment A:
![PXL_20220924_191345994 MP](https://user-images.githubusercontent.com/6307886/192114875-97a2cee2-059a-4ac6-84c3-e8da402d5b8d.jpg)
Also, the fully assembled 3d model that you link to shows an entirely different design for this part of segment A:
![Segment A Screw](https://user-images.githubusercontent.com/6307886/192114914-dffff536-4c05-4584-89e7-2a6290a7b262.png)
You probably ideally wouldn't use a screw for this anyway right? Since it's meant to pivot smoothly?

**Comment by madaeon01** [comment]
These are the most updated files:
https://3dsolutions.store/PF_files/LumiBee%20with%20plexi%20Expo%20box.STEP
WIth this model, 40mm screw is fine. Or you can use the Segment A you already printed and longer screws.

**Comment by MxRemy** [comment]
The latest version of the files have now been uploaded as STLs, as you said they solve this issue. Although I think it works better with a single long rod that's only threaded at the ends.
